### ISSUE TITLE
Logging out and keep baking

### ISSUE THREAD

**Issue by gaia** [bakechain/bakechain#1]
Running: Bakechain 0.2.0
OS: Win 10 1803 x64

It would benefit security if one could log out and keep baking.

I have a dedicated machine for baking, and it is windows locked, but I would feel safer if the wallet was also locked.

Thank you for your hard work, Stephen!

**Comment by stephenandrews** [comment]
The software needs to be unlocked in order to have access to your private key for baking

**Comment by aah180** [comment]
Hello and Thanks Stephen for that you have contributed.  Please pardon my noobish questions or comments.  My computer has to be on at all times to bake correct?  I can open a new tezbox wallet with my bakechain seed word and password because bakechain is not a spendable wallet correct?  I also need a tutorial on how to read the tz scanner. If there is any tutorials out there please let me know. Agsin thanks a bunch love your products!

**Comment by stephenandrews** [comment]
Correct - I'm unaware of any tutorials on tzsacan?
