### ISSUE TITLE
Is double baking fixed?

### ISSUE THREAD

**Issue by FlokiTheViking** [bakechain/bakechain#32]
Hi, I would like to begin using Bakechain but there are some comments on reddit alerting about Bakechain double-baking so I want to clarify them first:

- Is that double-baking bug already fixed with the 2 last updates?
- It would be safer in order to avoid double-baking to use you own node instead the public setup by default? And if so, is there any guide/tutorial in order to setup your own node using bakechain?
- Upon you are using Bakechain with the address created by default by the software, it will be possible when the Ledger Nano upgrade is released to use the same address in order to implement the Ledger Nano with the already baking address?

Thanks in advance Stephen, you are my hero

**Comment by stephenandrews** [comment]
1) Double baking has been fixed, unless you run multiple instances of the software with the same keys. I believe the latest user on reddit is not a bakechain user (someone on the Riot channels mentioned they lost bonds due to double baking, and they were not using bakechain - this occurred within the last 12 hours). Another user who lost bonds lately was most likely using an older version.

2) Running your node is always better, but doesn't really prevent double baking. The best way to setup your own remote-node is to follow this guide: https://github.com/tezoscommunity/FAQ/blob/master/Compile_Mainnet.md - you can buy a VPS from a solid provider, like Linode, AWS, Google Cloud or DigitalOcean. Once setup, you can use the node address within bakechain.

3) Ledger Nano S baking will be the best, as it will be more secure (due to on-device prevention's of double baking). However, you can not import existing addresses into the Ledger device, so unfortunately you will need to setup a new baking address. In saying that, Ledger baking with Bakechain should be released this week - going through final tests before release.

**Comment by stephenandrews** [comment]
And thanks for the kind words, means a lot!
