### ISSUE TITLE
v 2 Balance shows 0

### ISSUE THREAD

**Issue by rubenbur** [bakechain/bakechain#35]
![image](https://user-images.githubusercontent.com/39499802/48858107-6ebf8c80-ed6f-11e8-9c53-5f0157601b2e.png)

**Comment by FlokiTheViking** [comment]
It's happening to all Bakechainers, as Bakechain uses the same public nodes than Tezbox (https://rpc.tezrpc.me/), and since 7 hours ago are under high load (4-5x above usual high-load levels) as the following statement informs: https://twitter.com/TezBox_Wallet/status/1065203014644916224

If you try to use Tezbox you will find that the wallet cannot even recognise the address as part of the blockChain.

Let's pray that Stephen is working on it in order to fix the issue, there is nothing else we can do.

**Comment by stephenandrews** [comment]
Should be resolved with new release
